### ISSUE TITLE
Conditional Logic

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-formbuilder#62]
Implement Conditional Logic for Form Fields.

<img width="1033" alt="bildschirmfoto 2017-10-28 um 14 25 59" src="https://user-images.githubusercontent.com/700119/32134348-f382833e-bbeb-11e7-825a-4a0e6a908147.png">

## Conditional Logic Field
Every Form does have a conditional logic section.

### Conditions
| Condition  | Description  |
| :--------- |:--------|
| `field_value` | Choose between "is greater", "is less", "is exakt", "is checked", "not empty" of one ore more fields. |

### Actions
| Action  | Description  |
| :--------- |:--------|
| `toggle` | Change display state of one or more fields. |
| `change_constraints` | Change Validation of one ore more fields. |

### Todos I
- [x] Load Conditions and Actions from configuration
- [x] Store / Save Conditions in Backend
- [ ] ~~Highlight Form-Field Icon somehow if it's involved in one or more conditions or actions.~~
- [x] Apply CL to Frontend-Forms
- [x] Implement Constraint Switcher in PHP context

### Todos II
- [x] Frontend: Hide field require text in condition
- [x] Backend: set field `required` state of element to false if no validation available
